### ISSUE TITLE
Incremental bundling

### ISSUE THREAD

**Issue by julienrf** [scalacenter/scalajs-bundler#1]
Bundling time can be ~30 s for a 5k sloc project (~10 s if we disable source maps).

Investigate ways to perform incremental bundling using webpack-dev-server.

**Comment by sjrd** [comment]
One easy way to test in advance whether an AMD `ModuleKind` would work is to use a CommonJS-to-AMD converter, and time the results of working with the AMD module (discounting the time taken by the converter).

**Comment by julienrf** [comment]
Another solutions [suggested on gitter](https://gitter.im/scala-js/scala-js?at=5806910580020cc608f18a9d): bundle all the dependencies and export them to a way that can be directly used by the output of Scala.js (so that this output doesn’t need to be processed by webpack).

**Comment by nafg** [comment]
Have you looked into rollup instead of webpack? I've heard it's a lot faster.

**Comment by julienrf** [comment]
I will probably do some tests with rollup, yes.

**Comment by nafg** [comment]
https://github.com/scala-js/scala-js/issues/2175#issuecomment-172249250 implies rollup can take 1/4 the time webpack takes
