### ISSUE TITLE
How to integrate with HTML?

### ISSUE THREAD

**Issue by Tamriel** [scalacenter/scalajs-bundler#103]
I tried to recreate the official [tutorial](http://www.scala-js.org/tutorial/basic/), but with scalajs-bundler in my [repo](https://github.com/Tamriel/treepad). I compiled with `sbt fastOptJS::webpack` and opened the .html file. I got `Uncaught TypeError: (0 , $m_Lorg_scalajs_jquery_package$(...).jQuery$1) is not a function`.
Please provide an example with HTML files.

**Comment by julienrf** [comment]
Hi, there are several examples with HTML files, see for instance [static](https://github.com/scalacenter/scalajs-bundler/tree/master/sbt-scalajs-bundler/src/sbt-test/sbt-scalajs-bundler/static), [library](https://github.com/scalacenter/scalajs-bundler/tree/master/sbt-scalajs-bundler/src/sbt-test/sbt-scalajs-bundler/library) and [global-namespace](https://github.com/scalacenter/scalajs-bundler/tree/master/sbt-scalajs-bundler/src/sbt-test/sbt-scalajs-bundler/global-namespace).

**Comment by Tamriel** [comment]
Cool, thanks!

**Comment by Tamriel** [comment]
I adjusted the code of my repo above to the style of the library example. The code is beautiful, but I get the same error for my attempt to do a facade for the buffer js library. It would be very kind of you if you could take a look.

**Comment by julienrf** [comment]
Did you try with the trailing slash, as explained [here](https://github.com/feross/buffer#usage)? (ie. `@JSImport("buffer/", Namespace)`)

**Comment by julienrf** [comment]
Also, it seems that you want the `Buffer` member of the module, not the “namespace”: `@JSImport("buffer/", "Buffer")`

**Comment by Tamriel** [comment]
`@JSImport("buffer/", "Buffer")` worked, thank you very much!
