### ISSUE TITLE
Uncaught TypeError: Cannot read property 'freeze' of undefined

### ISSUE THREAD

**Issue by Tamriel** [scalacenter/scalajs-bundler#104]
I am trying to create a facade for avsc in my [repo](https://github.com/Tamriel/treepad). When I compile with `sbt fastOptJS::webpack` and open the .html file, I get `Uncaught TypeError: Cannot read property 'freeze' of undefined`. I would be glad for some help :-)

**Comment by julienrf** [comment]
Hi, I would recommend to post this kind of issues on stackoverflow or on gitter. Github issues are for bug reports rather than help.

**Comment by Tamriel** [comment]
Thanks for your help at [stackoverflow](http://stackoverflow.com/questions/42035261/typeerror-cannot-read-property-freeze-of-undefined/42038924#42038924) and sorry for posting here!
