### ISSUE TITLE
Migrating from manually including jquery to using bundle

### ISSUE THREAD

**Issue by abalonperin** [scalacenter/scalajs-bundler#109]
Hi,

I am trying to use `scalajs-bundler` for an existing project. I have successfully generated the `target/scala-2.11/scalajs-bundler/main/app-fastopt-bundle.js` file with `fastOptJS::webpack` after adding the npm dependency for `jquery 2.2.2` in `build.sbt` and included the `bundle.js` in my html file.

However, it seems that the code still doesn't have access to `jquery.js`. If I include a previously downloaded file `<script type="text/javascript" src="assets/javascript/jquery-2.2.2.min.js"></script>` in my html before the `app-fastopt-bundle.js`, everything works as it used to.

Here is my `NPM_DEPENDENCIES` file:
```
{"compile-devDependencies":[],"test-dependencies":[{"jquery":"2.2.2"}],"compile-dependencies":[{"jquery":"2.2.2"}],"test-devDependencies":[]}
```

Am I missing something?

Also, I am using the following import which afaict contains a facade to jQuery `import org.scalajs.jquery.jQuery`. 
Is there a reason why the tutorial explicitly requires to add the following code:
```
import org.scalajs.jquery.JQueryStatic
import scala.scalajs.js
import scala.scalajs.js.annotation.JSImport

@js.native
@JSImport("jquery", JSImport.Namespace)
object jquery extends JQueryStatic
```
Is the `scalajs-jquery` import not enough? It seems that whether I use the import or the custom code mentioned above, I get the same result.

Here is the exception that I get in the browser console:
```
Uncaught TypeError: (0 , $m_Lorg_scalajs_jquery_package$(...).jQuery$1) is not a function
```

I am still new to `scalajs` so sorry if these questions seem trivial. I have looked at the various examples provided for `static`, `global-namespace`, etc but so far I haven't been able to make it work.

Thank you very much in advance for your help

**Comment by julienrf** [comment]
In the generated bundle can you see that jQuery has been included? The code you gave should work. Maybe there is an issue specific to the jquery NPM module, in such a case you would probably get more help in the scalajs-jquery community.

**Comment by abalonperin** [comment]
Thank you for your quick reply.

It doesn't seem to be included. Did it work for you when running the example from the `README`? Would the jquery version have any impact on the result?

**Comment by julienrf** [comment]
Do you use the `jquery` object that you defined (the one with the `@JSImport` annotation) somewhere in your code?

**Comment by julienrf** [comment]
You *have to* use this facade instead of `org.scalajs.jquery.jQuery`.

**Comment by abalonperin** [comment]
I have tried with both codes without success.

**Comment by julienrf** [comment]
I would suggest you to share your code somewhere and ask help from the scalajs-jquery community.

**Comment by abalonperin** [comment]
understood. Thank you for your help and your great project. Hopefully I can make it work soon.
