### ISSUE TITLE
Lots of warnings about source map URLs

### ISSUE THREAD

**Issue by japgolly** [scalacenter/scalajs-bundler#111]
Examples:

Scala 2.12.1
```
[info] Cannot find source file 'https://raw.githubusercontent.com/scala/scala/v2.12.1/src/library/scala/collection/generic/IndexedSeqFactory.scala': Error: Can't resolve './https://raw.githubusercontent.com/scala/scala/v2.12.1/src/library/scala/collection/generic/IndexedSeqFactory.scala' in '/home/golly/projects/misc/target/scala-2.12/scalajs-bundler/main'
```

Scala.JS 0.6.14
```
[info] Cannot find source file 'https://raw.githubusercontent.com/scala-js/scala-js/v0.6.14/javalib/src/main/scala/java/util/regex/Pattern.scala': Error: Can't resolve './https://raw.githubusercontent.com/scala-js/scala-js/v0.6.14/javalib/src/main/scala/java/util/regex/Pattern.scala' in '/home/golly/projects/misc/target/scala-2.12/scalajs-bundler/main'
```

webpack prepends a `./` to everything.

**Comment by japgolly** [comment]
Raised: https://github.com/webpack/webpack/issues/4518

**Comment by julienrf** [comment]
I’m not sure of what we can do here :(

**Comment by japgolly** [comment]
We could filter out the warnings. More extreme, we could hack/patch webpack itself but I wouldn't recommend that. :) It's probably best to wait; I've raised an issue with webpack (above).

Also I think this issue should stay open here, not because there's any fault with scalajs-bundler, but because from a user's perspective, it *is* a bug that trickles down and will affects them with source maps on.

**Comment by bbarker** [comment]
Does this mean sourcemaps aren't  working, period? Even for project sources? It seems to be the case for me, but where should I be looking?

**Comment by OlegYch** [comment]
@julienrf was this ever released? i'm using 
```
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.26")
addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler" % "0.13.1")
```
https://github.com/scalacenter/scastie/blob/6f620f8101a9ae802cac8e33021e76d78433e5ec/project/plugins.sbt
but still get the warnings

**Comment by OlegYch** [comment]
@julienrf when was it released? i could perhaps try that version

**Comment by julienrf** [comment]
This was released with 0.13.0: https://scalacenter.github.io/scalajs-bundler/changelog.html#version-0.13.0

**Comment by shishkin** [comment]
I'm still getting these warnings with `"sbt-scalajs-bundler" % "0.14.0"`. I've patched `source-map-loader` (https://github.com/webpack-contrib/source-map-loader/pull/79) and was able use that patch with:

```
lazy val root = project
  .in(file("."))
  .enablePlugins(ScalaJSBundlerPlugin)
  .settings(
    inThisBuild(
      List(
        organization := "org.shishkin",
        version := "0.1-SNAPSHOT",
        scalaVersion := "2.12.8"
      )),
    name := "sample-app",
    libraryDependencies ++= Seq(
      "org.scala-js" %%% "scalajs-dom" % "0.9.6",
      "org.scalatest" %%% "scalatest" % "3.0.5" % "test"
    ),
    version in webpack := "4.28.1",
    version in startWebpackDevServer := "3.1.14",
    npmDevDependencies in Compile ++= npmDevOverrides,
    npmResolutions in Compile := npmDevOverrides.toMap,
    scalaJSUseMainModuleInitializer := true
  )
lazy val npmDevOverrides = Seq(
  "source-map-loader" -> "git+https://github.com/shishkin/source-map-loader#fetch-http-maps"
)
```

**Comment by julienrf** [comment]
Maybe this loader could help? https://github.com/aappddeevv/scalajs-friendly-source-map-loader

**Comment by joan38** [comment]
I hitting this too.

I tried your config @shishkin and got different error. It's now trying to resolve them locally but can't find them.
