### ISSUE TITLE
Provide separate setting key for node_modules target dir

### ISSUE THREAD

**Issue by jokade** [scalacenter/scalajs-bundler#116]
It would be great, if the target dir for `node_modules` could be set independently of the target dir where `webpack` is run. Since webpack will search parent dirs for `node_modules`, this allows to keep node modules outside of `target/` and thus avoid deleting it during `clean`.

**Comment by julienrf** [comment]
Good idea!

**Comment by julienrf** [comment]
Actually this is already possible: just set the `crossTarget in npmUpdate` setting to whatever you want.

**Comment by jokade** [comment]
I actually tried re-setting `(crossTarget in npmUpdate)`, however, the result of that is that all target files are put into that directory, whereas I think that the npmUpdate target should be independent from all `webpack` specific settings.
To this end, I propose to replace `(crossTarget in npmUpdate)` with a new setting `(crossTarget in webpack)` in the webpack tasks (I've done so in my fork, but now the `fastOptJS`t ask is no longer executed; I will create a pull request when I've solved this issue).

**Comment by julienrf** [comment]
Unfortunately I don’t think this is possible: node looks for modules in the `node_modules/` directory of the file that is currently processed. It means that the .js files *have to* be in the same directory as the `node_modules/` directory.

Alternatively, we could copy the output of `(fast|full)OptJS` into that directory just before running webpack and then copy the resulting bundles into another directory (e.g.`crossTarget in webpack`), but I’d like to keep things as simple as possible.

As a workaround, you can define your own sbt task that moves files were you want.

**Comment by jokade** [comment]
> Unfortunately I don’t think this is possible: node looks for modules in the node_modules/ directory of the file that is currently processed.

That's not quite true: I think `node` will travel up the directory hierarchy until it finds a directory with a `node_modules` in it (at least it works this way on macOS) -- this behaviour can also be a source for subtle bugs, if the required dependency is not found in the intended nodes_modules dir, but in a parent directory ... :(

**Comment by japgolly** [comment]
Yeah that's intended behaviour with nodejs:
https://nodejs.org/api/modules.html#modules_all_together
