### ISSUE TITLE
Automatically populate npmAdditionalNpmConfig description/licence/repository 

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalajs-bundler#133]
We're using scalajs-bundler in scalameta and get this error message
```
[error] npm WARN test No description
[error] npm WARN test No repository field.
[error] npm WARN test No license field.
```
https://travis-ci.org/scalameta/scalameta/jobs/241610752#L508-L510

I believe it's possible to silence those errors with npmAdditionalNpmConfig: https://github.com/scalacenter/scalajs-bundler/blob/ad42d1cdb77ae4b6eafa50b0e1013c1dd090aecc/sbt-scalajs-bundler/src/main/scala/scalajsbundler/sbtplugin/ScalaJSBundlerPlugin.scala#L140

It would be nice if those required fields would be set automatically, however.

**Comment by julienrf** [comment]
Indeed, the new `additionalNpmConfig` key makes it easy for users to implement this.

But I agree that we could provide it out of the box :)

**Comment by japgolly** [comment]
You can also avoid this by setting `"private": true` in the generated `package.json`.

eg. default:
```
> cat package.json
{
}

> npm install     
npm WARN node No description
npm WARN node No repository field.
npm WARN node No license field.
```
and private
```
> cat package.json
{
  "private": true
}

> npm install     
```
