### ISSUE TITLE
npmUpdate can be very slow (because it occurs twice - once each for main and test)

### ISSUE THREAD

**Issue by somanythings** [scalacenter/scalajs-bundler#144]
Since introducing scalajs-bundler, our ci build times have more than doubled. 
We've tracked down that this is largely because npmUpdate is run - once each for main and test. 
Previously - we did have a step in our build that ran npm-cache. This grabs the npm packages from a specifiable local cache (much like maven or ivy does with .m2). 
I've taken a look at the scalajs-bundler code, but my sbt-fu is, perhaps, a little weak. I can't see a convenient seam where I could install a pre-hook. 
I think I could have just copied and modified npmUpdate locally in our build but 

```
private val scalaJSBundlerPackageJson =
  | TaskKey[File]("scalaJSBundlerPackageJson", "Write a package.json file defining the NPM dependencies of project", KeyRanks.Invisible)
```

, which I think we need for the packageJson creation, is private. 

Hopefully I've just mis-understood something, and someone's kind enough to educate me, and close this issue. Otherwise, tell me how I can get around that. Failing that, tell me to submit a PR, or tell me you've given me the seam (or make me even happier, and give the option of npm-cache)

Thanks for all the effort so far, very appreciated, it helped cleanup our build process significantly, just sadly at the expense of significant time!

**Comment by julienrf** [comment]
Does the problem also happen if you use Yarn instead? Switching to Yarn might be a simpler solution.

**Comment by somanythings** [comment]
Dramatically better, I'd searched the code for "cache" - but neglecting to try caching. Thanks!
