### ISSUE TITLE
"How to use an existing facade ..." cookbook recipe doesn't describe testing with jsdom case

### ISSUE THREAD

**Issue by pwlmaciejewski** [scalacenter/scalajs-bundler#145]
I've found that this recipe https://scalacenter.github.io/scalajs-bundler/cookbook.html#global-namespace works well for standard dev or prod build scenario. When it comes to testing with `requiresDOM in Test := true` case it fails to load global modules. 

From what I've found in the source it looks like testing is handled differently: https://github.com/scalacenter/scalajs-bundler/blob/8d1d7fed5ee87e5e526b523540d3b377f90fe1ad/sbt-scalajs-bundler/src/main/scala/scalajsbundler/sbtplugin/ScalaJSBundlerPlugin.scala#L652

I've managed to get my setup working but with slightly different webpack config:

```js
var globalModules = {
  moment: "moment"
};

var config = {
  module: {
    loaders: [
      {
        // Force require global modules
        test: /.*-fastopt\.js$/,
        loader: "imports-loader?" + Object.keys(globalModules).map(function(modName) {
          return modName + "=" + globalModules[modName];
        }).join(',')
      },
      Object.keys(globalModules).map(function(modName) {
        // Expose global modules
        return {
          test: require.resolve(modName),
          loader: "expose-loader?" + globalModules[modName]
        }
      })
    ]
  }
};

module.exports = config;
```

It uses [imports-loader#0.7.0](https://github.com/webpack-contrib/imports-loader/tree/v0.7.0) to force require of global modules so prepending globals to entries is no longer needed. It can be put into `common.webpack.config.js` and then reused in both `dev.webpack.config.js` and `test.webpack.config.js` by merging with [webpack-merge](https://github.com/survivejs/webpack-merge).

Maybe it's worth updating the cookbook for this scenario? Or is there maybe a easier way to achieve the same resul?

**Comment by julienrf** [comment]
We should at least add a [test case / example](https://github.com/scalacenter/scalajs-bundler/tree/master/sbt-scalajs-bundler/src/sbt-test/sbt-scalajs-bundler) with this configuration. It is not clear to me why the `import-loader` makes things work in test mode, can you elaborate why? Also, we should probably update the cookbook entry with your solution, since it seems to address more use cases than the current one. Would you mind creating a PR for that?

**Comment by pwlmaciejewski** [comment]
The difference between dev and test build is that in dev build you want to import generated config and then you can prepend global modules to entries. In test build `./scalajs.webpack.config' is not generated (at least for me). Instead webpack is called like this: 

```
webpack --config [path_to_custom_webpack_config] path_to_CodeWithJsDOMContext.js some_output_path
``` 
So as you can see it's impossibe to prepend globals. 

I'm not a webpack expert but `imports-loader` does the trick for me: in example below it's like writing `var lib = require('somelib')` at the top of the `foo.js`:

```js
{
  test: /^foo\.js$/,
  loader: "imports-loader?lib=somelib"
}
```

As for the PR, sure will post one later this week.
