### ISSUE TITLE
Add Windows support

### ISSUE THREAD

**Issue by julienrf** [scalacenter/scalajs-bundler#15]
Currently, the `npm` command is not found on windows.

**Comment by julienrf** [comment]
@DylanArnold Can you confirm me that it works for you on Windows with the 0.2.1 version? Did you encounter any other issue?

**Comment by DylanArnold** [comment]
Yes. Works the same with 0.2.1 on windows.

I did just read the contributing.md however and ran sbt scripted. This fails on windows both on 0.2.1 and pre my PR, seems to be an unrelated bug. Are you aware of that?

A quick sift through the logs and I extracted some notable lines: 

I think these may warrant a separate issue though, let me know what you think.

```
[info] [error] Uncaught exception when running example.ExampleSpec: java.lang.NoClassDefFoundError: example/Routes (wrong name: example/routes)
[info] sbt.ForkMain$ForkError: java.lang.NoClassDefFoundError: example/Routes (wrong name: example/routes)
```


```
[info] [info] *** 1 SUITE ABORTED ***
[info] [error] Error: Total 1, Failed 0, Errors 1, Passed 0
[info] [error] Error during tests:
[info] [error]  example.ExampleSpec
[info] [error] (server/test:test) sbt.TestsFailedException: Tests unsuccessful
```

```
[info] [error] C:\Users\Dylan\AppData\Local\Temp\sbt_b067a4e8\facade\usage\src\main\scala\example\Foo.scala:3: object uuid is not a member of package uuid
[info] [error] import uuid.uuid
[info] [error]        ^
[info] [error] C:\Users\Dylan\AppData\Local\Temp\sbt_b067a4e8\facade\usage\src\main\scala\example\Foo.scala:7: object v4 is not a member of package uuid
[info] [error]   def bar(): String = uuid.v4()
```

```
[info] + sbt-scalajs-bundler / static
java.lang.RuntimeException: Failed tests:
        sbt-web-scalajs-bundler / play
```

```
java.lang.RuntimeException: Failed tests:
        sbt-scalajs-bundler / facade
```

**Comment by julienrf** [comment]
Wow, yes that’d be great if you could create two separate issues for these problems. You can separately reproduce them easily by running the following sbt commands: `sbt "sbt-scalajs-bundler/scripted sbt-scalajs-bundler/facade"` and `sbt "sbt-web-scalajs-bundler/scripted sbt-web-scalajs-bundler/play"`. Please post the complete stack trace. In the meanwhile I will try to setup a Windows development environment so that I can investigate on my own.
