### ISSUE TITLE
Publish for SBT 1.0.0

### ISSUE THREAD

**Issue by shadaj** [scalacenter/scalajs-bundler#150]
Now that SBT 1.0.0 has been released, it would be great to have the plugin support it.

**Comment by aparo** [comment]
Is there any update to this issue?

**Comment by julienrf** [comment]
I didn't work on it but any contribution is welcome. I guess the issue is ready to be solved because the Scala.js plugin already supports sbt 1.0. We should also check for sbt-web-scalajs.

**Comment by nafg** [comment]
sbt-web-scalajs was published for sbt 1. https://github.com/vmunier/sbt-web-scalajs/pull/38#issuecomment-325633686

**Comment by rleibman** [comment]
I've got a good chunk of it done, I think. I had to upgrade a bunch of the plugins and modify the build.sbt slightly. The only thing currently blocking me is that there's no version of the OrnatePlugin for sbt 1.0,

I'm working holistically (i.e. not understanding anything) at this point, I just want things to compile.

**Comment by sjrd** [comment]
I highly recommend not to try and update the *build* itself to sbt 1.0. This requires that all the sbt plugins used by *the build* (as opposed to by the plugin) be available for 1.0.

Instead, the build should use sbt 0.13.16, and then you can use `^^1.0.1` to build the plugin itself against sbt 1.0. This is by a large margin the path of least resistance.

**Comment by rleibman** [comment]
I'm not sure what you mean by ^^1.0.1, where do I type that? is that something I add to the build.sbt, or is it a command in sbt?

**Comment by julienrf** [comment]
I agree with @sjrd, migrating the plugin only (without migrating the build) is quite easy actually (we just have to change some file manipulation and `sbt.Process` usage). Actually I tried to do the migration a few days ago, it works OK but I got a dozen of false positive errors because of this issue: https://github.com/sbt/sbt/issues/3299. I was thinking of waiting for it to be fixed before actually making the migration.

**Comment by jonas** [comment]
Started work on this (sorry @rleibman, didn't see your message until now).

#179 bumps dependencies and fixes several problems when building with sbt 1.0 such as
```
[error] Problem: `useYarn` is inside the if expression of a regular task.
[error]   Regular tasks always evaluate task inside the bodies of if expressions.
```

[jonas/scalajs-bundler@sbt-1.0](https://github.com/jonas/scalajs-bundler/tree/sbt-1.0) contains WIP to do the final upgrade. The main blocker is [this snippet](https://github.com/scalacenter/scalajs-bundler/blob/master/sbt-web-scalajs-bundler/src/main/scala/scalajsbundler/sbtplugin/WebScalaJSBundlerPlugin.scala#L74-L85) inside sbt-web-scalajs-bundler, which gives this error:
```
[error] /opt/scalajs-bundler/sbt-web-scalajs-bundler/src/main/scala/scalajsbundler/sbtplugin/WebScalaJSBundlerPlugin.scala:84: The evaluation of `foldLeft` inside an anonymous function is prohibited.
[error]
[error] Problem: Task invocations inside anonymous functions are evaluated independently of whether the anonymous function is invoked or not.
[error]
[error] Solution:
[error]   1. Make `foldLeft` evaluation explicit outside of the function body if you don't care about its evaluation.
[error]   2. Use a dynamic task to evaluate `foldLeft` and pass that value as a parameter to an anonymous function.
[error]
[error]             .foldLeft(Def.task(Seq.empty[((File, String), Boolean)]))((acc, bundleFiles) => Def.task(acc.value ++ bundleFiles.value))
[error]                                                                      ^
[error] one error found
```
