### ISSUE TITLE
yarn.lock is not version controlled.

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalajs-bundler#151]
The yarn lock is in the target directory. It should be version controlled. I suggest it should go in the project `baseDirectory`. For example, `client/baseDirectory`.

> In order to get consistent installs across machines, Yarn needs more information than the dependencies you configure in your package.json. Yarn needs to store exactly which versions of each dependency were installed.

https://yarnpkg.com/lang/en/docs/yarn-lock

**Comment by fdietze** [comment]
How difficult is this? With some instructions I could try to contribute a fix. I believe that this will speed up and stabilize many of CI-builds.

**Comment by fdietze** [comment]
Yarn is executed here: https://github.com/scalacenter/scalajs-bundler/blob/c6a534eca1056dcb06506a5cb7cae00f2e32f034/sbt-scalajs-bundler/src/main/scala/scalajsbundler/ExternalCommand.scala#L47

But yarn doesn't seem to have a command line flag to specify the lockfile path...

**Comment by MasseGuillaume** [comment]
@fdietze you can copy the lockfile both ways and make sure it's in sync.
