### ISSUE TITLE
fastOptJS::webpack does not run if webpackConfigFile dependencies changes

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalajs-bundler#159]
in my webpackConfigFile I have a shared configuration like:

```js
const Common = require('./webpack.common.js');
```

If I touch `webpack.common.js` and I run `fastOptJS::webpack` it does not bundle.

**Comment by MasseGuillaume** [comment]
https://scalacenter.github.io/scalajs-bundler/cookbook.html#custom-config

maybe I can add this file via `webpackMonitoredDirectories`

**Comment by easel** [comment]
I believe such files should be covered by webpackResources, and I'm pretty sure I specifically added them to the dependencies to the webpackLibraries task in https://github.com/scalacenter/scalajs-bundler/pull/149. If you have a second to check it against your workflow it would cool

**Comment by julienrf** [comment]
@MasseGuillaume Can you confirm that the bug is still present?
