### ISSUE TITLE
Add dependency metadata in jars

### ISSUE THREAD

**Issue by mkotsbak** [scalacenter/scalajs-bundler#16]
I assume the recursive dependencies must now be added manually.

It woule be nice if metadata about the npm dependencies would have been added to the jar in a file similar to JS_DEPENDENCIES used for webjars. Maybe it should be possible to disable in case the user wants to include it manually.

**Comment by julienrf** [comment]
Recursive dependencies are not supported but transitive dependencies are. There is a [test for that](https://github.com/scalacenter/scalajs-bundler/tree/master/sbt-scalajs-bundler/src/sbt-test/sbt-scalajs-bundler/facade). Do you have a failing use case?

**Comment by julienrf** [comment]
@mkotsbak I’m closing this issue, feel free to re-open it with more information.
