### ISSUE TITLE
yarn npm update dependencies fails with unknown flag

### ISSUE THREAD

**Issue by easel** [scalacenter/scalajs-bundler#164]
I'm not sure the version of yarn that's now required, with version 0.18.1 which appears to be the latest npm will give me, I get the following.

[info] Updating NPM dependencies
[error]
[error]   error: unknown option `--non-interactive'

**Comment by julienrf** [comment]
This option has been added in version 0.22.0: https://github.com/yarnpkg/yarn/releases/tag/v0.22.0. We should definitely mention that requirement in the docs.
