### ISSUE TITLE
Migrate @JSExport usages to @JSExportTopLevel

### ISSUE THREAD

**Issue by julienrf** [scalacenter/scalajs-bundler#169]
`@JSExport` is deprecated and will be removed in Scala.js 1.0

**Comment by exoego** [comment]
I suppose that this issue can be closed without migration.
I tried to make PR for this issue originally, but then realized that there are perhaps no need for migration.

`@JSExport` are deprecated to export objects, classes, and static members of objects. And `@JSExportTopLevel` came in for such usages. https://www.scala-js.org/news/2017/03/21/announcing-scalajs-0.6.15/

However, I believe that `@JSExportTopLevel` is not allowed to export the instance members of classes. For such usage, `@(JSExport @field)` is still required.

In scalajs-bundler code base,  there are 3 files that uses `@JSExport` to export instance members of case classes. So I think there might be no need for migration.

https://github.com/scalacenter/scalajs-bundler/blob/6236326bc97656ae99e81d9ae4ba4124a3270510/sbt-scalajs-bundler/src/sbt-test/sbt-scalajs-bundler/browserless/src/main/scala/uuid/uuid.scala#L46
https://github.com/scalacenter/scalajs-bundler/blob/6236326bc97656ae99e81d9ae4ba4124a3270510/sbt-scalajs-bundler/src/sbt-test/sbt-scalajs-bundler/library/src/main/scala/uuid/uuid.scala#L46
https://github.com/scalacenter/scalajs-bundler/blob/6236326bc97656ae99e81d9ae4ba4124a3270510/sbt-scalajs-bundler/src/sbt-test/sbt-scalajs-bundler/facade/facade/src/main/scala/uuid/uuid.scala#L43

Please correct me if my understanding is wrong. I would like to make PR for this issue.

**Comment by exoego** [comment]
FYI. This is my WIP branch for this issue. 
https://github.com/exoego/scalajs-bundler/commit/a6d9f46c7347a91da11fb030a5c91b7373f0661c

Tests are enhanced so that we can test the instance member of case class is actually exported to JavaScript (`uuid` module).

**Comment by julienrf** [comment]
Thanks @exoego for having a look at it! Looking again at this issue I think I wrote a wrong description.

I still see some warnings when we compile our examples (and our plugin). The initial idea behind this issue was to get rid of these warnings to be prepared for the next releases of Scala.js.

I see for instance a warning [here](https://ci.appveyor.com/project/julienrf/scalajs-bundler/build/470/job/834nrlsheh4jg8o9#L2267). In that case we could just trade the `class` for a `trait`.

Another warning that we could fix is [that one](https://ci.appveyor.com/project/julienrf/scalajs-bundler/build/470/job/834nrlsheh4jg8o9#L421) (completely unrelated to `@JSExport`).

**Comment by julienrf** [comment]
Actually the cases I’ve linked above already have dedicated issues (#168 and #181). So I think we should close this one.
