### ISSUE TITLE
both fastOpt and fullOpt produce scalajs.webpack.config.js

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalajs-bundler#170]
```scala
val webpackConfigFile = targetDir / "scalajs.webpack.config.js" // TODO discriminate filename according to sjs stage
```

**Comment by julienrf** [comment]
Can you elaborate on why this is a problem for you?

If we use distinct file names, then users writing a custom webpack config file will have to take care of which generated config file name to require.

**Comment by MasseGuillaume** [comment]
Yeah I think, I will just not use this file. Basically, in my prod config I want fullOpt

**Comment by julienrf** [comment]
So:

> Can you elaborate on why this is a problem for you?

**Comment by MasseGuillaume** [comment]
None.
