### ISSUE TITLE
Add to docs, that BundlerMode.Library* may be not compatible with some js libs via global scope in production

### ISSUE THREAD

**Issue by helllamer** [scalacenter/scalajs-bundler#178]
Hi. 

This crazy issue occurs only in `fullOptJS`.

We have a really FAT internal project, that uses `leaflet.js` from scala.js.
Historically, Leaflet is living in global `L` variable, and only last months there are some support for CommonJS appearing.

But Leaflet still binds global `window.L` for backward compatibility (btw, i'm not tested latest version of leaflet).

After switching to `scalajs-bundler-0.8.0`, project stopped to work in production `fullOptJS` mode, when `webpackBundlingMode := BundlingMode.LibraryOnly()` or `LibraryAndApplication()` also.
```
TypeError: L is not a function
UY(http://localhost:9000/vassets/d1a0d84e7b66ee8617dd736af8cca5ba-app-opt.js:2032:130)
... (tl;dr useless stacktrace) ...
```

As you guessed it, leaflet global `L` somehow conflicts with `var L=` from minified `app-sjs-opt.js` source.

!!!! But when `webpackBundlingMode` is defaulted, **production build works as expected**.

I unsure, it is a bug or not.
Possible, documentation highlights or warnings will be enought...

UPD1: Also, i cannot provide test-case, because the issue is very floating and unstable.

UPD2: Leaflet 1.2.0 (latest version) -- same problem. Used #177 as workaround.

**Comment by easel** [comment]
Have you tried defining leaflet as a webpack "external"? It should be possible to reserve it's global variable and skip attempting to bundle it by doing so.

**Comment by helllamer** [comment]
According to docs, externals should solve the problem, but `leaflet.js` will need another `<script src="...">` tag on the pages. Not so big price, will try...

**Comment by helllamer** [comment]
Found `L.noConflict()` in leaflet sources, that resets global namespace back to default.
This should be enough.
