### ISSUE TITLE
Dependency unresolved 0.8.0

### ISSUE THREAD

**Issue by DavidWhit** [scalacenter/scalajs-bundler#182]
This is probably a quick fix though I don't see the issue other than everywhere it tried to get the build for 8 doesn't seem to have a valid response.

I have
     sbt 1.0.2
     scalajs 0.6.20
      scala 2.12

On the setup page I don't see anything I'm doing different and here is the error log after adding the repo. 

addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler" % "0.8.0") 

in plugins.sbt thoughts?

[warn]  module not found: ch.epfl.scala#sbt-scalajs-bundler;0.8.0
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/ch.epfl.scala/sbt-scalajs-bundler/scala_2.12/sbt_1.0//0.8.0/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/ch.epfl.scala/sbt-scalajs-bundler/scala_2.12/sbt_1.0//0.8.0/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\WD031\.ivy2\local\ch.epfl.scala\sbt-scalajs-bundler\scala_2.12\sbt_1.0\\0.8.0\ivys\ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/ch/epfl/scala/sbt-scalajs-bundler_2.12_1.0/0.8.0/sbt-scalajs-bundler-0.8.0.pom
[warn] ==== local-preloaded-ivy: tried
[warn]   C:\Users\WD031\.sbt\preloaded\ch.epfl.scala\sbt-scalajs-bundler\0.8.0\ivys\ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:/C:/Users/WD031/.sbt/preloaded/ch/epfl/scala/sbt-scalajs-bundler_2.12_1.0/0.8.0/sbt-scalajs-bundler-0.8.0.pom
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? [warn]    ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: ch.epfl.scala#sbt-scalajs-bundler;0.8.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          ch.epfl.scala:sbt-scalajs-bundler:0.8.0 (scalaVersion=2.12, sbtVersion=1.0)

**Comment by scalavision** [comment]
Same thing happened to me, when trying to build locally I get compile errors ...

**Comment by tematema** [comment]
Looks like there is sbt 0.13 support only:
https://repo1.maven.org/maven2/ch/epfl/scala/sbt-scalajs-bundler_2.10_0.13/

**Comment by DavidWhit** [comment]
Are their plans to support sbt >= 1 ?

**Comment by sjrd** [comment]
It's already on master: https://github.com/scalacenter/scalajs-bundler/pull/179

**Comment by DavidWhit** [comment]
Thanks guys! I appreciate this; close whenever

**Comment by larochef** [comment]
Hi everyone, when do you think there will be a release? Anything missing for it?

**Comment by Daxten** [comment]
I already used it with publishLocal, so not sure what's missing?

**Comment by dispalt** [comment]
@julienrf released 0.9.0
