### ISSUE TITLE
Using sbt-web support prevents Intellij Idea from importing the project

### ISSUE THREAD

**Issue by skvithalani** [scalacenter/scalajs-bundler#189]
We have a minimal project in [branch sbt-web](https://github.com/skvithalani/monitoring-server-spike/tree/sbt-web) which uses WebScalaJSBundlerPlugin and ScalaJSBundlerPlugin as documented. 

Works great from sbt but fails to load in IntelliJ with the following error. We are using IntelliJ Idea 2017.2.5 with latest Scala Plugin 2017.2.11. Tried with node versions 6.x as well as 8.x.

Has anyone else faced it, if so is there a known workaround? Thanks.

`Error:Error while importing SBT project:<br/>...<br/><pre>[error] 	at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:142)
[error] 	at scalajsbundler.sbtplugin.WebpackTasks$.$anonfun$webpack$1(WebpackTasks.scala:48)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (server/*:ssExtractDependencies) java.io.IOException: Cannot run program "node" (in directory "/Users/salonivithalani/Desktop/tw_tmt/monitoring-server-spike/client/target/scala-2.12/scalajs-bundler/main"): error=2, No such file or directory
[error] Total time: 3 s, completed Nov 7, 2017 3:15:20 PM
[INFO] [11/07/2017 15:15:20.437] [Thread-4] [CoordinatedShutdown(akka://sbt-web)] Starting coordinated shutdown from JVM shutdown hook</pre><br/>See complete log in <a href="file:/Users/salonivithalani/Library/Logs/IntelliJIdea2017.2/sbt.last.log">file:/Users/salonivithalani/Library/Logs/IntelliJIdea2017.2/sbt.last.log</a>`

**Comment by glmars** [comment]
The main is: `Cannot run program "node" (in directory "/Users/salonivithalani/Desktop/tw_tmt/monitoring-server-spike/client/target/scala-2.12/scalajs-bundler/main"): error=2, No such file or directory`
Are there any `node` executable in `%PATH%`? (please, check by `where node` and `echo %PATH%` commands)

**Comment by skvithalani** [comment]
Thanks for the response. We confirmed that "node" was globally set at latest version. But still we got the error (mentioned in this issue) while loading the project in intellijIDEA.

So, we came up with a work around. The trick was to disable `server` module to depend on `client` module when the project was loaded in intelljIDEA and enable it when it was loaded in sbt.

We made a flag available from sbt shell and decided based on that for `server` to depend on `client`. We modified the [build.sbt](https://github.com/skvithalani/monitoring-server-spike/blob/sbt-web/build.sbt) for that and made sure to load sbt shell only via a [shell script](https://github.com/skvithalani/monitoring-server-spike/blob/sbt-web/sbt) .

**Comment by skvithalani** [comment]
It turns out that intellijIDEA uses different PATH than that is SET in environment variable.

More details is explained in the blog [fix PATH environment variable for IntelliJ IDEA on Mac OS X](http://depressiverobot.com/2016/02/05/intellij-path.html)

As a solution I created a shell script

>#!/usr/bin/env bash
open -a "IntelliJ IDEA"

and made it execute at login [refer this answer to launch an executable at login](https://stackoverflow.com/questions/6442364/running-script-upon-login-mac/13372744#13372744)

It seems others have also faced the same problem but with other plugins which can be referred [here](https://github.com/Transmode/gradle-docker/issues/65)

**Comment by skvithalani** [comment]
It seems that the issue is entirely with intellijIDEA which can be tracked [here](https://youtrack.jetbrains.com/issue/SCL-12898).

Hence, closing this ticket.
