### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by zartstrom** [scalacenter/scalajs-bundler#193]
I set up a minimal project and after adding scalajs-bundler I get this error in the browser console:
```scalajsenv.js:26 Uncaught ReferenceError: exports is not defined```

The scalajs code I took from the scalajs tutorial.
```scala
package tutorial.webapp

import org.scalajs.dom
import dom.document

object TutorialApp {
  def main(args: Array[String]): Unit = {
    appendPar(document.body, "Hello world!")
  }

  def appendPar(targetNode: dom.Node, text: String): Unit = {
    val parNode = document.createElement("p")
    val textNode = document.createTextNode(text)
    parNode.appendChild(textNode)
    targetNode.appendChild(parNode)
  }
}
```
This is my build.sbt
```scala
enablePlugins(ScalaJSPlugin,ScalaJSBundlerPlugin)
/*enablePlugins(ScalaJSPlugin)*/

name := "Scala.js Tutorial"
scalaVersion := "2.12.2" // or any other Scala version >= 2.10.2

scalaJSUseMainModuleInitializer := true

libraryDependencies ++= Seq(
  "org.scala-js" %%% "scalajs-dom" % "0.9.1"
)
```
and my plugins.sbt and build.properties
```scala
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.21")
addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler" % "0.9.0")
```
```
sbt.version=1.0.3
```
and finally the html:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>The Scala.js Tutorial</title>
  </head>
  <body>
      <div id="test"></div>

    <!-- Include Scala.js compiled code -->
    <script type="text/javascript" src="./target/scala-2.12/scalajs-bundler/main/scala-js-tutorial-fastopt.js"></script>
    <!--<script type="text/javascript" src="./target/scala-2.12/scala-js-tutorial-fastopt.js"></script>-->
  </body>
</html>
```

I want to use https://github.com/fdietze/scala-js-d3v4 and kept removing all d3 stuff from my example code to get to the code above.
Surely I do miss something obvious?!

**Comment by edude03** [comment]
I ran into the same issue, the problem is you need to load the `-bundle` file as noted here https://github.com/scalacenter/scalajs-bundler/issues/147

**Comment by zartstrom** [comment]
Hi @edude03 thanks for your help.
I don't have the solution yet. In the html I include
```<script type="text/javascript" src="./target/scala-2.12/scalajs-bundler/main/scala-js-tutorial-fastopt.js"></script>```
This is the only js file I have in my filesystem besides `./target/scala-2.12/scala-js-tutorial-jsdeps.js`.
So I'm not sure what #147 is referring to when talking about "including -bundle.js".

**Comment by edude03** [comment]
@zartstrom don't forget to run webpack - something like `sbt fastOptJS::webpack`

**Comment by zartstrom** [comment]
`sbt fastOptJS::webpack` did the trick. I didn't notice that adding the plugin changes the way I create the js.
Thanks for your help!
