### ISSUE TITLE
Additional JS resources

### ISSUE THREAD

**Issue by mathieuleclaire** [scalacenter/scalajs-bundler#194]
Hi,
I neet to includes some additional resources required by a main js files depending on options set or not. 

Typically, when you use the ace editor (I have no problem to fetch the ace.js main file throug npmDependencies), I want to add a particular code grammar (scala for instance !) located in a submodules of the webpack directory (in node_modules/brace/mode/scala.js), I didn't find any trick to 1) automatically include it in the big js and 2) to render it available in the code (like a require(xxx)). 

I tried this:
```scala 
  webpackMonitoredFiles in webpack in fullOptJS in Compile += ((webpack in fullOptJS in Compile).value.head.data).getParentFile / "node_modules/brace/mode/scala.js",
```
But it does not deals with the require() part, so that the scala gramar js is not available at runtime.

I guess I neet a webpack js config ... It would be usefull to make it available directly in the scalajs-bundler API !
Any idea ?

Thanks
Mathieu

**Comment by fdietze** [comment]
Here is an example that could help: https://github.com/scalacenter/scalajs-bundler/tree/master/sbt-scalajs-bundler/src/sbt-test/sbt-scalajs-bundler/js-resources

**Comment by mathieuleclaire** [comment]
This example describes how to embedd an JS, for whom we built a facade. This part is fine for me: my ace.js is correctly merged. But I would also need to add an additional js, which is located in a subdirectory of node_modules/brace.

**Comment by julienrf** [comment]
`@JSImport("brace/mode/scala.js", …)`?

**Comment by mathieuleclaire** [comment]
Hi,
I would like to know if this recommendation is still valid (it has been 2 years now)?

I used to load my js ace modes and theme manually, but I get often issues: the mode is sometimes not loaded properly. I guess it is because I do not do it so well as webapck does ! 
To load the main ```ace.js```, I have a this in my ace facade (the npm package is called ace-builds):
```scala
@js.native
@JSImport("ace-builds", JSImport.Namespace)
object ace extends js.Object {
```
It works perfectly and I can load my ace editor properly. 

But the ```session.setMode("ace/mode/scala")```, that I used to use to apply the scala color highlighting by providing the mode-scala.js manualy in a big js file does not work here. I tried several options (npmAssets, webpack config files) but I didn't succeeded in solving this. 
I observe that I don't get any mode-scala js anywhere in the stuff produced by webpack (except in the dowloaded `node_modules/ace-builds/src-noconflict` repository), and I get this message in the browser debugger:
```
Loading failure for the <script> element whose source is "file:///home/mathieu/work/cogit/scaladget/demo/target/mode-scala.js".
```
meaning that Ace try to load mode-scala.js from the root directory.

I hope my description is clear. How could I solve this ?

**Comment by mathieuleclaire** [comment]
To achieve this I ned:
1) defining in my facade a new JSImport:
```scala
@js.native
@JSImport("ace-builds/src-noconflict/mode-scala.js", JSImport.Namespace)
object scalamode extends js.Object
```
and
2) Call this ```scalamode``` in my program entry point, because _Webpack only includes modules that are “used”, in the resulting bundle_
