### ISSUE TITLE
Non *.js required files provided in resources folder but missing in target/scala-2.11/scalajs-bundler/

### ISSUE THREAD

**Issue by christobill** [scalacenter/scalajs-bundler#201]
Let's say I want to use `my-module.js` in my project
It requires `config.json`
```
 src/main/resources/config.json
 src/main/resources/my-module.js
```

src/main/resources/my-module.js looks like:
```
var uuid = require('uuid');
var config = require('./config.json');

console.log(JSON.stringify(config));

module.exports = {
  someUuid: uuid.v4()
};
```

the corresponding facade:
```
package example

import scala.scalajs.js
import scala.scalajs.js.annotation.JSImport

@JSImport("./my-module", JSImport.Namespace)
@js.native
object MyModule extends js.Object {
  val someUuid: String = js.native
}
```

and the main:
```
package example

import scala.scalajs.js.JSApp

object Main extends JSApp {

  def main(): Unit = {
    println(MyModule.someUuid)
  }

}
```

I get the following error:
```
[info] Running example.Main
[error] module.js:544
[error]     throw err;
[error]     ^
[error] Error: Cannot find module './config.json'
[error]     at Function.Module._resolveFilename (module.js:542:15)
[error]     at Function.Module._load (module.js:472:25)
[error]     at Module.require (module.js:585:17)
[error]     at require (internal/module.js:11:18)
```

**Comment by julienrf** [comment]
We currently delegate to `scalaJSNativeLibraries` to collect these resources but we might want to make this process more extensible and allow users to define more resources. We could do that by introducing a `scalaJSResources` key whose default value would be `scalaJSNativeLibraries.value`.

**Comment by sjrd** [comment]
Note that `scalaJSNativeLibraries` will go away in Scala.js 1.x. So instead of defaulting to `scalaJSNativeLibraries.value`, it would be a good opportunity to make it default to the copy-paste of the implementation of `scalaJSNativeLibraries` from https://github.com/scala-js/scala-js/blob/e66844601a58f6141df0ad5bb7d5600c0c57c781/sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala#L619-L623

**Comment by ant8e** [comment]
Given that `scalaJSNativeLibraries` will go away and that having `src/main/resources` containing js source file is odd to begin with I suggest the following :
  - Deprecate the current behaviour
  - Introduce a concept of a js source directory (`src/main/js` by default) whose entire content will be collected
