### ISSUE TITLE
fastOptJS::webpack should invalidate when relevant build.sbt settings change

### ISSUE THREAD

**Issue by ryan-williams** [scalacenter/scalajs-bundler#206]
If I run `fastOptJS::webpack`, change `scalaJSUseMainModuleInitializer`, then `reload` and run it again, the change is not picked up. 

I have to `clean` (including re-resolving NPM dependencies) before `fastOptJS::webpack` will reflect the `scalaJSUseMainModuleInitializer` change.

[Full repro here](https://github.com/ryan-williams/scala-bugs/tree/sjs), you can try commenting the `scalaJSUseMainModuleInitializer` line in `build.sbt`, rerunning `fastOptJS::webpack`, and observing no change until a `clean`.

**Comment by sjrd** [comment]
FWIW, Scala.js core is partially to blame, here. The core plugin doesn't invalidate its `fastOptJS` either when `scalaJSUseMainModuleInitializer` or `scalaJSLinkerConfig` changes. `clean`ing is the standard workaround.

**Comment by ryan-williams** [comment]
thanks, filed at scala-js, closing here, feel free to reopen if there is actually a bundler-specific issue
