### ISSUE TITLE
MainModuleInitializer doesn't work without deprecated JSApp

### ISSUE THREAD

**Issue by codingismy11to7** [scalacenter/scalajs-bundler#207]
I've been successfully using the `scalaJSUseMainModuleInitializer := true` option with an object extending `JSApp`.  Since that's deprecated, I removed it and started getting

```
[error] (client/compile:scalaJSModuleInitializers) No main module initializer was specified (possibly because no or multiple main classes were found), but scalaJSUseMainModuleInitializer was set to true. You can explicitly specify it either with `mainClass := Some(...)` or with `scalaJSMainModuleInitializer := Some(...)`
```

I've tried setting `mainClass := Some("client.Main")` and `scalaJSMainModuleInitializer := Some(mainMethod("client.Main", "main"))`, but the same error keeps happening.

**Comment by sjrd** [comment]
If you don't extend `JSApp`, your main `object` needs to have a
```scala
def main(args: Array[String]): Unit = ...
```
method (with `extends JSApp` it was `def main(): Unit`)

**Comment by codingismy11to7** [comment]
sorry, I assumed it was an issue when the bundler was mixed in, guess i should have read the sjs docs more closely. on the other hand, the bundler example project could use an update, i'll try to open a PR if i get time.
