### ISSUE TITLE
The bundling task is called twice when using the fast live-reloading workflow

### ISSUE THREAD

**Issue by julienrf** [scalacenter/scalajs-bundler#22]

**Comment by Sebruck** [comment]
Somehow i can't reproduce this, @julienrf could you give some more details please?

**Comment by julienrf** [comment]
First, thanks for having a look at this issue!

Here is the way I work:
 - I modify the test file of a test I’m interested in (in your case, the `sbt-web-scalajs-bundler/play/test` file) to add a `$ pause` at the beginning.
- Then I run the test (in your case `> sbt-web-scalajs-bundler/scripted sbt-web-scalajs-bundler/play`)
- When the test is in pause, I spawn a new console, go to the test directory (in `/tmp/sbt_xxx`) in which I run sbt (`$ sbt -Dplugin.version=0.5.0-SNAPSHOT`).
- Here I can play with sbt commands, tweak the build.sbt file, see what happens, etc.

In your case, in the last step you want to run the server, load the page in your browser, change something in the client source file, and refresh the page in your browser.

In the console, you might see the message “bundling the application” two times in a row after each refresh. I don’t understand why…

Note that maybe it happens only when the reload workflow is enabled (which is not anymore the case, by default, in the 0.5.0).

Does that help?

**Comment by dispalt** [comment]
It definitely happens to me too, and yes I have the reloadWorkflow enabled.  I'll try to take a look tonight too.

**Comment by dispalt** [comment]
I think it's specific to the play integration, not entirely sure how to fix it though

**Comment by dispalt** [comment]
Leaving a note here, but this is the best I've found in terms of symptoms appearing elsewhere.  https://github.com/playframework/playframework/issues/5242

**Comment by julienrf** [comment]
The issue seems to be on Play’s side.

**Comment by julienrf** [comment]
The problem can be fixed by setting the following config in the server project:

~~~ scala
WebKeys.exportedMappings in Assets := Seq()
~~~
