### ISSUE TITLE
Use project-level custom NPM registry

### ISSUE THREAD

**Issue by mariussoutier** [scalacenter/scalajs-bundler#224]
Neither setting a custom registry using `.npmrc` nor `package.json` seems to work. Only `npm config set registry` is recognized. So scalajs-bundler should allow setting a project-level registry.

**Comment by cquiroz** [comment]
Have you tried `additionalNpmConfig`? Can you specify extra repos on `package.json`?

**Comment by matthughes** [comment]
You got me hopeful this morning with these suggestions but it doesn't work.  I think the best solution be to have npmArgs as was suggested in gitter that lets you pass random args to the npm invocation.  That way, you can set the registry (and anything else) just for that invocation.  I might take a stab at the PR if I find some time.

**Comment by cquiroz** [comment]
ok, I'll try to add that params, same as for yarn

**Comment by cquiroz** [comment]
see #254

**Comment by cquiroz** [comment]
Can you confirm that `0.13.1` lets you fix this issue?

**Comment by matthughes** [comment]
Yup!  Works great:

```
 npmExtraArgs ++= Seq(
      "--registry=https://nexus.local/nexus/content/groups/npm-public/"
    ),
```

Thanks so much!
