### ISSUE TITLE
update document for npmAssets

### ISSUE THREAD

**Issue by WayneWang12** [scalacenter/scalajs-bundler#231]
In the section of [npmAssets](https://scalacenter.github.io/scalajs-bundler/reference.html#npm-assets), it says:
```
npmAssets ++= NpmAssets.ofProject(client) { nodeModules =>
  (nodeModules / "font-awesome").***
}.value
```

However, in sbt 1.0, the method `***` is renamed to `.allPaths` method. I think it must be better if the document points this(though I think it's sbt's fault because it's not using `@deprecated` but just do a rename).

**Comment by mathieuleclaire** [comment]
It seems the doc is now up to date and this issue can be closed.
