### ISSUE TITLE
Does scalajs-bundler work with cross-built projects?

### ISSUE THREAD

**Issue by dragonfly-ai** [scalacenter/scalajs-bundler#235]
Some information visualization features in a cross compiled Scala.js project depend on Singular Value Decomposition, SVD.  On the JVM side, JAMA provides the functionality, but it looks like numeric.js might work best on the JavaScript side.

After following the getting started guide, watching dependencies download, and typing "fastOptJS::webpack" the numeric variable remains undefined in the browser.

This project could dramatically improve the dev and deployment process, but not if I can't get it working.  Help?

**Comment by julienrf** [comment]
Hello, this is not really the best place to ask for help. You should rather use gitter.im. That being said, yes, scalajs-bundler should work with cross-built projects. At least I’m using it in a cross-built project. Can you share your build.sbt?

**Comment by dragonfly-ai** [comment]
Thanks, Julien.  I will move the topic there.

**Comment by evbo** [comment]
scalajs bundler definitely supports cross projects, I'd recommend closing this issue (would if I could)

**Comment by cquiroz** [comment]
Yes this is very old and we should close it
