### ISSUE TITLE
Documentation code samples are blank

### ISSUE THREAD

**Issue by evbo** [scalacenter/scalajs-bundler#280]
I think this was working as recently as yesterday, but today the code snippets aren't displaying, e.g.:

https://github.com/scalacenter/scalajs-bundler/blob/master/manual/src/ornate/cookbook.md#how-to-get-and-use-a-list-of-assets

Inspecting in developer tools for that element, I see:
```
<p>You can this list e.g. with <a href="https://github.com/sbt/sbt-native-packager">sbt-native-packager</a>` to add mappings as:</p>
<div class="highlight highlight-source-scala"><pre></pre></div>
```

**Comment by julienrf** [comment]
You are browsing the source of the documentation. The rendered documentation is available here: https://scalacenter.github.io/scalajs-bundler/cookbook.html#how-to-get-and-use-a-list-of-assets

**Comment by evbo** [comment]
ah, thanks and sorry - mindlessly clicking on what google serves me!
