### ISSUE TITLE
[0.15.0] %%% resolves to 1.0.0-M7

### ISSUE THREAD

**Issue by PuneetPatwari** [scalacenter/scalajs-bundler#295]
After upgrading to 0.15.0 when I add dependency `"io.scalajs" %%% "nodejs" % "0.4.2"`, I get the following error `io.scalajs#nodejs_sjs1.0.0-M7_2.12;0.4.2: not found`.

**Comment by julienrf** [comment]
Hello, indeed the index page of the documentation has not been updated but the [getting started](https://scalacenter.github.io/scalajs-bundler/getting-started.html#basic-setup) page shows that to work with Scala.js 0.6.x you have to use the `0.15.0-0.6` version of scalajs-bundler.

**Comment by PuneetPatwari** [comment]
Hi, Thanks for the quick response. I had missed the importance of this tag in the releases. Your clarification helped. It works now.
