### ISSUE TITLE
Provision to specify artifactName explicitly on fullOpt::webpack task

### ISSUE THREAD

**Issue by skvithalani** [scalacenter/scalajs-bundler#297]
We are trying to publish a npm library using scalajs-bundler and if we go by the convention we want to have our entry file in our library named as `index.js` but the plugin creates the artifact name by appending `-bundle.js` to fastOpt/fullOpt.

So, is it feasible to provide a sbt setting to take artifactName from the user and generate webpack resource as per that name (i.e. value of `artifaceName`) instead of projectName-opt-bundle when running `fullOptJS::webpack`?

**Comment by julienrf** [comment]
Why don't you publish your library as a CommonJS module (the de facto standard)?

**Comment by skvithalani** [comment]
I think I was not very clear with my first comment. Let me re-phrase it. In sbt I get a setting `fullOptJS/artifactPath` which allows to get(set) artifact generation path by fullOptJS.

Similarly, is there a sbt setting `fullOptJS/webpack/artifactPath` that allows me to get(set) artifact generation path by webpack ?  If not, can we add it ?

**Comment by julienrf** [comment]
Does it work if you use a custom webpack config file and set the `output.filename` setting? (I prefer trying to not introduce new features in scalajs-bundler unless they are critical)

**Comment by skvithalani** [comment]
@julienrf 

`output.filename` in webpack works well with what we are trying to achieve. Hence, we can close the issue.

**Comment by julienrf** [comment]
Awesome, thanks for your investment!
