### ISSUE TITLE
Bump Scala.js to 1.0.0-RC1

### ISSUE THREAD

**Issue by julienrf** [scalacenter/scalajs-bundler#300]
The Scala.js 1.x support currently only works with 1.0.0-M7.

We should update to RC1 (we would drop M7 support), and run the tests to see if more work is needed to get things working.

**Comment by nafg** [comment]
Make that RC1

**Comment by dejvid** [comment]
Anny planing to support Scala.js 1.0.0-RC1 Soon? Is there a way to help.

**Comment by sjrd** [comment]
There's definitely a way to help! Clone the repo, bump the Scala.js version and try to make things work :)

**Comment by julienrf** [comment]
Closed by #316
