### ISSUE TITLE
scalajs-bundler 0.16.0 fails to fastOptJS with Scala.js 1.0.0

### ISSUE THREAD

**Issue by exoego** [scalacenter/scalajs-bundler#329]
I made a repro repo https://github.com/exoego/scalajs1-runtimelong-issue

```
git clone https://github.com/exoego/scalajs1-runtimelong-issue.git
cd scalajs1-runtimelong-issue

# will fail
sbt fastOptJS::webpack

# this also will fail
sbt test
```

The error message looks like `org.scalajs.ir.IRVersionNotSupportedException: Failed to deserialize a file compiled with Scala.js 1.0-RC1 (supported up to: 1.0): org/scalajs/linker/runtime/RuntimeLong.sjsir`

**Comment by sjrd** [comment]
You need to add the following line in `project/plugins.sbt`:
```Scala
libraryDependencies += "org.scala-js" %% "scalajs-linker" % "1.0.0"
```
to work around the issue.

It's also already completely solved on master. We'll try to publish a new release before the official announcement of Scala.js 1.0.0.
