### ISSUE TITLE
small documentation typo: emitSourceMaps should be webpackEmitSourceMaps

### ISSUE THREAD

**Issue by evbo** [scalacenter/scalajs-bundler#342]
With `0.17.0` this cookbook recipe is no longer accurate:
https://scalacenter.github.io/scalajs-bundler/cookbook.html#performance

It has been refactored and should read:
```sbt
webpackEmitSourceMaps := false
```

didnt see any documentation PRs in flight so I thought it'd be useful to point out ;)

**Comment by evbo** [comment]
also, perhaps a bigger issue is that I don't seem to be able to disable emitting source maps. Ultimately I'm just disabling them inside chrome devtools. I've cleaned my target directory ensuring nothing was left over, unless chrome somehow caches them...

**Comment by fdietze** [comment]
This works for me:

```
webpackEmitSourceMaps in fullOptJS := false,
```

**Comment by evbo** [comment]
looks like this was fixed - thanks
