### ISSUE TITLE
NoSuchMethodError with sbt-web-scalajs 1.1.0

### ISSUE THREAD

**Issue by nafg** [scalacenter/scalajs-bundler#354]
In https://github.com/vmunier/sbt-web-scalajs/releases/tag/v1.1.0 isDevMode doesn't exist, instead it uses scalaJSStage which is a setting built into the scalajs sbt plugin. Using 0.18 with it therefore results in a NoSuchMethodError

**Comment by LolHens** [comment]
Could we get a new release with #351?

**Comment by nafg** [comment]
I believe this should be closed, since 0.19.0 and 0.20.0 have been released
