### ISSUE TITLE
0.20: Bundler misses require() in JSImported+extended class

### ISSUE THREAD

**Issue by helllamer** [scalacenter/scalajs-bundler#381]
Sidebar.scala
```
@JSImport("react-sidebar", JSImport.Default)
@js.native
class SidebarJs(props: SidebarProps) extends js.Object {
  def componentDidMount(): Unit = js.native
}

class SidebarForcedJs(props: js.Object) extends SidebarJs(props) {
  override def componentDidMount(): Unit = { ..... }
}

val component = JsComponent[js.Object, Children.Varargs, js.Object]( js.constructorOf[SidebarForcedJs] )
```

build.sbt:
```
enablePlugins(ScalaJSBundlerPlugin)

npmDependencies in Compile ++= Seq(
  "react-sidebar" -> "3.0.2"
)
```
As you can see, `JSImport`ed code is touched only via `class ... extends JsClass`.

In `scalajs-bundler-0.20`, stacktrace occurs in any web-browser:
```
$i_react$002dsidebar is not defined
$a_Lcom_github_balloob_react_sidebar_SidebarForcedJs (Sidebar.scala:42)
$c_Lcom_github_balloob_react_sidebar_Sidebar$ (Sidebar.scala:19)
$m_Lcom_github_balloob_react_sidebar_Sidebar$ (Sidebar.scala:17)
...
```

`project-fastopt-library.js` **misses** the line:
```
const $i_react$002dsidebar = require("react-sidebar");
```

`project-fastopt.js` contains lines:
```
$b_Lcom_github_balloob_react_sidebar_SidebarForcedJs = class $b_Lcom_github_balloob_react_sidebar_SidebarForcedJs extends $moduleDefault($i_react$002dsidebar) {
....
}
```
where `$i_react$002dsidebar` is always undefined.

`BundlingMode.LibraryOnly()` or `Application` - error occurs in both modes.

=== Current workarounds ===
The source of problem located in `class ... extends ...` keyword in v0.20, so... :
1. Do not use `extend` for imported JS-class, always use raw `SidebarJs` class directly. 
2. OR There are no problems in `scalajs-bundler-0.18` nor in `fastOptJS`, neither in `fullOptJS` with any bundling mode.

**Comment by sjrd** [comment]
* What about v0.19.0?
* What versions of Scala.js are you using with the respective versions of scalajs-bundler?

**Comment by helllamer** [comment]
Sorry, forgot some info:
- I've tested sjs-1.3.0 against bundler-0.20.
- And also sjs-1.2.0 against bundler-0.18 and 0.20.

Ok, I'll prepare testcase for problem.

**Comment by helllamer** [comment]
0.19 - problem also occurs.

**Comment by helllamer** [comment]
@sjrd 
Reproduceable test-case is here:
https://github.com/helllamer/scalajs-bundler-issue-381-testcase

Steps to reproduce:
1. `sbt test`
It will fail with:
```
[info] com.github.balloob.react.sidebar.SidebarSpec
[info] - sjs-component should be usable *** FAILED ***
[info]   JavaScriptException: ReferenceError: $i_react$002dsidebar is not defined
[info]     $a_Lcom_github_balloob_react_sidebar_SidebarForceIosJs(webpack:///./scalajs-react-sidebar-test-fastopt.js?:16200:146)
...
```


Steps to work-around:
1. In `project/plugins.sbt` change sjs and bundler versions to `1.2.0` and `0.18` respectively
2. `sbt test`
Test will success.

**Comment by sjrd** [comment]
Thanks for the repro. It appears to be a bug in Scala.js itself, because the import already does not exist in the `fastopt.js` file, although it is used.

**Comment by sjrd** [comment]
Here is a workaround that does not require downgrading the versions: add a reference to `js.constructorOf[SidebarJs]` somewhere in code that gets executed. For example, before the code that wants to use `SidebarForceIosJs`:
```diff

 object Sidebar {
+
+  // Workaround scalajs-bundler#381
+  js.constructorOf[SidebarJs]

   val component = JsComponent[SidebarProps, Children.Varargs, SidebarState]( js.constructorOf[SidebarForceIosJs] )

   def apply(props: SidebarProps)(children: VdomNode*) = component( props )(children: _*)

 }
```

**Comment by sjrd** [comment]
Closing in favor of https://github.com/scala-js/scala-js/issues/4268
