### ISSUE TITLE
__webpack_require__ cannot read property

### ISSUE THREAD

**Issue by mathieuleclaire** [scalacenter/scalajs-bundler#40]
Hi,
I tried scalajs-bundler to package my project scaladget. Scladget exposes several facades for js libs (one of them is a DSL on top of [bootstrap.native](https://thednp.github.io/bootstrap.native/)). In my build.sbt, I construct the scaladget lib and I build another project demo to run some demos of the lib. I'd like to make my scaladget lib depends on the bootstrap.native npm and then make my demo depends on my scaladget lib. I get the following build. The runDemo key constructs the fullOptJS, set the js target in a demo.js file and the webpack target is stored in a scaladget.js file.

```sbt
lazy val scaladget = project.in(file("scaladget")) settings(
  libraryDependencies += "org.scala-js" %%% "scalajs-dom" % scalaJSdomVersion,
  libraryDependencies += "com.lihaoyi" %%% "scalatags" % scalatagsVersion,
  libraryDependencies += "com.lihaoyi" %%% "scalarx" % rxVersion,
  npmDependencies in Compile += "bootstrap.native" -> bootstrapNativeVersion
  ) enablePlugins(ScalaJSBundlerPlugin, ScalaJSWeb) settings (defaultSettings: _*)


lazy val runDemo = taskKey[Unit]("runDemo")

lazy val demo = project.in(file("demo")) dependsOn (scaladget) enablePlugins(ScalaJSBundlerPlugin, WebScalaJSBundlerPlugin) settings (defaultSettings: _*) settings(
  libraryDependencies += "com.lihaoyi" %%% "scalarx" % rxVersion,
  libraryDependencies += "com.lihaoyi" %%% "sourcecode" % sourceCodeVersion,
  libraryDependencies += "org.scala-lang" % "scala-reflect" % ScalaVersion % "provided",
  scalaJSModuleKind := NoModule,
  runDemo := {
    val demoTarget = target.value
    val demoResource = (resourceDirectory in Compile).value
    IO.copyFile((fullOptJS in Compile).value.data, demoTarget / "js/demo.js")
    (webpack in fullOptJS in Compile).value.foreach { f =>
      IO.copyFile(f, demoTarget / "js/scaladget.js")
    }
    IO.copyFile(demoResource / "index.html", demoTarget / "index.html")
    IO.copyDirectory(demoResource / "js", demoTarget / "js")
    IO.copyDirectory(demoResource / "css", demoTarget / "css")
    IO.copyDirectory(demoResource / "fonts", demoTarget / "fonts")
  )
```
 Then both js are called from my index.html: demo.js from the header and scalaget.js as the final instruction of the Boostrap.main() method (it is a requirement of bootstrap.native).

```html
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="stylesheet" type="text/css" href="css/bootstrap.min-3.3.7.css">
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <link rel="stylesheet" type="text/css" href="css/github-gist.css">
    <script type="text/javascript" src="js/demo.js"></script>
    <script src="js/highlight.pack.js"></script>
</head>
<body onload="demo.BootstrapDemo().main();"></body>
</html>
```

When calling the demo.BoostrapDemo().main() method, the following error occurs:
```js
scaladget.js:47Uncaught TypeError: Cannot read property 'BootstrapDemo' of undefined(anonymous function)
```
refering to the scaladget.js file (47):

```js
__webpack_require__(1)["demo"]["BootstrapDemo"]().main()
```
The scaladget.js file is attached as a txt file: [scaladget.txt](https://github.com/scalacenter/scalajs-bundler/files/613730/scaladget.txt)

I guess I missed something but I do not understand what. Do I use the scalajs-bundler plugins properly ? 
Thanks for helping and congrats for this developpement !

Mathieu

**Comment by julienrf** [comment]
Hi, you should not set the `scalaJSModuleKind` to `NoModule` when using the module bundler. Let it be `CommonJSModule`.

Also, can you show me the code of your facade and the way you use it?

Last, I’m not totally sure but I think the right scope for the `webpack` task is `webpack in (Compile, fullOptJS)`.

**Comment by mathieuleclaire** [comment]
Hi, this two modifications lead to this:
```sh
demo.js:2 Uncaught ReferenceError: exports is not defined
index.html:13 Uncaught ReferenceError: demo is not defined
```
That's why I had switched from NoModule to CommonJSModule.
And my facade is this:
```scala
import org.scalajs.dom.Element
import scala.scalajs.js

@js.native
class Modal(element: Element) extends js.Object {

  def open(): Unit = js.native
  def close(): Unit = js.native
}
```
I tried to use JSImport, but I didn't understand how to use it, but it is certainly the key !

**Comment by julienrf** [comment]
Indeed you have to use `@JSImport`. Does [this section](https://scalacenter.github.io/scalajs-bundler/cookbook.html#facade) help? Can you elaborate on what’s unclear?

**Comment by julienrf** [comment]
In your case, I guess you want to write the following: `@JSImport("bootstrap.native", "Modal")`

**Comment by julienrf** [comment]
Could you share a project from which I can reproduce the issue, please?

The first parameter of `@JSImport` is the CommonJS module name, as explained in the [documentation](https://www.scala-js.org/doc/interoperability/facade-types.html#a-nameimporta-imports-from-other-javascript-modules)

**Comment by julienrf** [comment]
BTW, why are you enabling the `WebScalaJSBundlerPlugin` on the `demo` project?

**Comment by mathieuleclaire** [comment]
Yes I do. I pushed my modifications in the scalajsbundler branch in the repo [https://github.com/openmole/scaladget](https://github.com/openmole/scaladget). Launch the runDemo key. And then open the demo/target/index.html. Thanks !

**Comment by julienrf** [comment]
I fixed the problem here: https://github.com/openmole/scaladget/pull/8

**Comment by mathieuleclaire** [comment]
Yes, it works fine ! Thanks. This plugin is really amazing. It render possible to build really smart libs !

**Comment by julienrf** [comment]
Good to know that it works for you :)
