### ISSUE TITLE
(newb) Is there a way to get the image optimisation and CSS rewriting?

### ISSUE THREAD

**Issue by yatesco** [scalacenter/scalajs-bundler#405]
Hi there - real newbie here :-).

Using `create-react-app` (etc.) the production process bundles all images into a single sprite stream and rewrites the CSS to refer to that singe image. 

Is this the responsibility of this plugin, and if so, how, or should I be looking at ScalaJS-react for this? 

Thanks!

**Comment by cquiroz** [comment]
Not really a responsibility of the plugin but you can make webpack do it. Scalajs-bundler in turn calls webpack

**Comment by yatesco** [comment]
Thanks - I’ll close this issue but if you have any links you could send, I would be very grateful :-)
