### ISSUE TITLE
is npm ci supported?

### ISSUE THREAD

**Issue by evbo** [scalacenter/scalajs-bundler#406]
I am noticing my `package-lock.json` file hasn't been getting honored by npm (not related to scalajs-bundler I don't think), which causes serious bugs due to slide versioning causing minor releases to be downloaded instead of static versions you've developed against.

[What seems to definitely be the most certain way to enforce building using `package-lock.json`](https://stackoverflow.com/questions/45022048/why-does-npm-install-rewrite-package-lock-json) is running `npm ci` instead of `npm install`.

Is there a way to trigger this behavior through scalajs-bundler? I am currently cding into the target directory and running `npm ci` as a separate step:

```shell
(cd client/target/scala-2.13/scalajs-bundler/main/ && npm ci)
```

Is there a way to automate this as part of the sbt build?

**Comment by zoombinis** [comment]
background on issue here: https://stackoverflow.com/questions/45022048/why-does-npm-install-rewrite-package-lock-json?rq=1

This would be a [relatively small refactor](https://github.com/scalacenter/scalajs-bundler/blob/0d8812f9d019ecf8aad151c54b98374b8aa87c9a/sbt-scalajs-bundler/src/main/scala/scalajsbundler/ExternalCommand.scala#L123), allowing the npm "install" command to be subbed for "ci", and would add great CI capability for those building in a Jenkins environment that want guarantees everything is freshly installed from a package-lock file.

Even with npm `7.20.5` this issue with npm install is mysterious to me. Running with a package-lock file bundled I get the wrong version installed, e.g.:
```shell
modules# grep -nr -A 1 "electron-to-chromium" .
./electron-to-chromium/package.json:2:  "name": "electron-to-chromium",
./electron-to-chromium/package.json-3-  "version": "1.3.799",
```

but manually running npm ci everything is expected (`1.3.752` is in my package-lock):
```bash
modules# grep -nr -A 1 "electron-to-chromium" .
./electron-to-chromium/package.json:2:  "name": "electron-to-chromium",
./electron-to-chromium/package.json-3-  "version": "1.3.752",


```

Any interest in supporting npm ci in scalajs bundler from devs?

**Comment by ptrdom** [comment]
This will be implemented with https://github.com/scalacenter/scalajs-bundler/pull/420 by allowing you to specify install command through settings.

**Comment by evbo** [comment]
awesome!
