### ISSUE TITLE
NPM dependencies

### ISSUE THREAD

**Issue by mathieuleclaire** [scalacenter/scalajs-bundler#42]
Hi,
I have two questions on NPM dependencies:
1) is it possible to restrict the required files from the NPM source ? Something like:
```sbt
"myNPM" -> theVersion / "dist/thisJS.js" 
```
2) is it possible to embedd css too through the NPM dependencies ? For instance:
```sbt
"myNPM" -> theVersion / "dist/thisCSS.css" 
```

Thanks !

**Comment by julienrf** [comment]
Hi,

> is it possible to restrict the required files from the NPM source ?

Yes, but you will apply the restriction at the `@JSImport` level, not the `npmDependencies` level:

~~~ scala
@JSImport("myNPM/dist/thisJS.js", JSImport.Namespace)
@js.native
object ThisJSFacade extends js.Object { … }
~~~

> is it possible to embedd css too through the NPM dependencies?

I’m not sure, maybe by using webpack loaders. I just opened #43 for this specific concern.

I will close this issue as this is more a question than an issue. Feel free to re-open it if you consider that I should fix something.

**Comment by mathieuleclaire** [comment]
Thanks !
