### ISSUE TITLE
Getting java.lang.IllegalStateException: Linker used concurrently

### ISSUE THREAD

**Issue by nafg** [scalacenter/scalajs-bundler#47]
Using 0.3.0, I sometimes get:

```
> ~fastOptJS::webpack
[info] Compiling 1 Scala source to /home/naftoli/dev/gitlab.com/nafg/qbmeetup-tictactoe/target/scala-2.11/classes...
[info] Fast optimizing /home/naftoli/dev/gitlab.com/nafg/qbmeetup-tictactoe/target/scala-2.11/qbmeetup-tictactoe-fastopt.js
[trace] Stack trace suppressed: run last compile:fastOptJS for the full output.
[error] (compile:fastOptJS::webpack) java.lang.IllegalStateException: Linker used concurrently
[error] Total time: 3 s, completed Nov 30, 2016 1:30:23 AM
```

Here's my build.sbt:

```scala
name := "qbmeetup-tictactoe"

version := "1.0"

scalaVersion := "2.11.8"

enablePlugins(ScalaJSBundlerPlugin)

resolvers += Resolver.jcenterRepo

libraryDependencies += "io.github.nafg" %%% "sri-web" % "0.6.0-M1"

jsDependencies ++= Seq(
  "org.webjars.bower" % "react" % "15.3.1" / "react-with-addons.js" minified "react-with-addons.min.js" commonJSName "React",
  "org.webjars.bower" % "react" % "15.3.1" / "react-dom.js" minified "react-dom.min.js" dependsOn "react-with-addons.js" commonJSName "ReactDOM",
  "org.webjars.npm" % "history" % "3.0.0-2" / "history.js" minified "history.min.js"
)
```

**Comment by julienrf** [comment]
Hey @nafg, I also noticed this error a few times.

BTW, as explained in the [Scala.js documentation](https://www.scala-js.org/doc/interoperability/facade-types.html#a-nameimporta-imports-from-other-javascript-modules), the usage of JavaScript modules is not compatible with `jsDependencies`. You should turn your webjars dependencies into `npmDependencies in Compile`

**Comment by nafg** [comment]
Yeah, I was using it npmDependencies first, but then I realized Sri would have to be ported to use it. I then realized Scala-js-bundler wasn't adding anything and removed it. But it could be the error was even at first.

**Comment by julienrf** [comment]
Actually the issue does not seem to have been completely fixed.

**Comment by julienrf** [comment]
I’m closing it since it seems the problem hasn’t happened for a while.
