### ISSUE TITLE
Duplicate dependencies in package.json when a project depends on several sub-projects

### ISSUE THREAD

**Issue by julienrf** [scalacenter/scalajs-bundler#48]
Example of generated `package.json` file for scalajs-react:

~~~ javascript
{
  "dependencies": {
    "react-dom": "15.3.2",
    "sizzle": "2.3.0",
    "react-addons-test-utils": "15.3.2",
    "react-dom": "15.3.2",
    "sizzle": "2.3.0",
    "react-addons-test-utils": "15.3.2",
    "react": "15.3.2",
    "react-dom": "15.3.2",
    "react-addons-perf": "15.3.2",
    "react-addons-css-transition-group": "15.3.2"
  },
  "devDependencies": {
    "webpack": "1.13",
    "concat-with-sourcemaps": "1.0.4",
    "source-map-loader": "0.1.5"
  }
}
~~~

We should group dependencies by name and check that for each one there is no more than one version (in such a case, we should emit a warning and arbitrarily select the first one).

**Comment by sjrd** [comment]
> arbitrarily select the first one

Why not the one with the highest version number?

**Comment by julienrf** [comment]
> Why not the one with the highest version number?

Versions could be things like `"~1.0"` or `">=1.2.7"`. It would be cumbersome to write an ordering relationship for that. It is probably better to not try to be too smart and let users resolve the version they want to use.

**Comment by sjrd** [comment]
OK but arbitrarily select the first element of an inherently unordered set of dependencies is the worst possible thing to do.

Maybe a reasonable choice would be to accept if all agree, and demand a resolution strategy otherwise.

**Comment by julienrf** [comment]
@nstojiljkovic Are you still working on this one? I could take care of it, otherwise.

**Comment by nstojiljkovic** [comment]
@julienrf feel free to take it, I won't have time this week :(
