### ISSUE TITLE
Custom loader script for nodejs

### ISSUE THREAD

**Issue by MHOOO** [scalacenter/scalajs-bundler#62]
I'm trying to invoke my application via nodejs, however this requires me to pass a bootstrap struct
```
{
        "__dirname": __dirname,
        "__filename": __filename,
        "exports": exports,
        "module": module,
        "require": require
}
```
via a bootstrap javascript file (this is how [transcendent](https://github.com/ldaniels528/transcendent.js) does it), to my JSApp main function. I do this, so I can e.g. require modules like express from within my JSApp via the passed nodejs "require" function.

Only problem is that requiring the generated webpack bundle does not export a main fn, so I am unable to invoke it with the bootstrap struct. I suspect it would be possible to write a custom loader using sbt that invokes the JSApp.main() with the necessary struct - then that would be invoked upon requiring the webpack - but I'm wondering whether there is a simpler way?

**Comment by julienrf** [comment]
If I understand correctly you want to use nodejs to run a program generated by Scala.js, and this program makes use of some npm packages. So, you would like these dependencies to be bundled with the program. You might want to use the webpack “library” export mode (but for this to work you will have to use the trick explained in #59).

Another approach could be to *not* use webpack at all. Instead, just use the output of Scala.js as a nodejs module (and use the `package.json` file generated by scalajs-bundler to get its dependencies).

**Comment by sjrd** [comment]
The bootstrap used by Transcendent is basically a workaround for Scala.js *not* having `@JSImport` and direct CommonJS support in the past. Using this bootstrap method together with scalajs-bundler is an oxymoron, I think.

Eventually Transcendent should migrate to a model based on `@JSImport` and native CommonJS support from Scala.js. In the meantime, you could adapt the bridge with the `Bootstrap` not to use bootstrap. Instead of their documentation:
```scala
def start(bootstrap: Bootstrap) = {
  import bootstrap._

  val express = require[Express]("express")
  ...
}
```
you could do:
```scala
@js.native
@JSImport("express", JSImport.Namespace)
object ExpressBootstrap extends js.Object

def start() = {
  val express = ExpressBootstrap.asInstanceOf[Express]
  ...
}
```

**Comment by MHOOO** [comment]
I see. Manually loading express via JSImport in my main does work. However, what about libraries (e.g. transcendent or scalajs-react) that do not utilize JSImport internally. Won't they be unable to find the necessary dependencies? For example, scalajs-react uses the "React" singleton internally, that does not use JSImport. As such, the react module doesn't get pulled into the scalajs-react module namespace. Is there a work-around for that?

**Comment by sjrd** [comment]
For top-level singletons like `React`, nothing should change (I think), but you will probably have to leave the `react.js` library out of the Webpack treatment or something like that.

**Comment by julienrf** [comment]
@MHOOO I think @sjrd and I answered your questions, should I close this issue?

**Comment by MHOOO** [comment]
Yes, that did help, many thanks. But not quite there yet.

- I can successully use transcendent, via the work-around of srjd (i.e. a JSImport of react(-dom) on a dummy object), which will make sure that react/react-dom is included inside the resulting bundle. Furthermore however, since transcendent is internally using "React" as a top-level global identifier, I also needed to extend the webpack config with (this took me 2 days to figure out - explaining my late reply ^^):
```
module.exports.module.loaders = [
    // Make sure that react is available to e.g. the scalajs-react facade
    {test: require.resolve("react"), loader: "expose?React"},
    {test: require.resolve("react-dom"), loader: "expose?ReactDOM"}
]
```
and my sbt config with the "expose-loader" npm dependency. So far so good.

Now, I'm using a library called "rc-tabs" which contains a css file under 
node_modules/rc-tabs/assets/index.css

I've tried requiring that file via
```
// @JSImport("~rc-tabs/assets/index.css", JSImport.Default)
@JSImport("!style-loader!css-loader!~rc-tabs/assets/index.css", JSImport.Default )
  @js.native
object RcTabsAssets extends js.Object {}
```
However, it doesn't appear that this is working:
```
[info] ERROR in ./frontend-fastopt.js
[info] Module not found: Error: Cannot resolve module '~rc-tabs/assets/index.css' in /home/thomas/data/gitspace/scalajs-webapp/app-frontend/target/scala-2.11
[info]  @ ./frontend-fastopt.js 1031:100-161
```

I'm not exactly sure whether this is still related to scalajs-bundler or webpack and am just posting here in hopes someone may know the answer.

**Comment by MHOOO** [comment]
Ok, found my mistake. The "~" was unnecessary, so the following:
```
@JSImport("!style-loader!css-loader!rc-tabs/assets/index.css", JSImport.Default )
  @js.native
object RcTabsAssets extends js.Object {
```}
does work (after depending on both style-loader & css-loader in npmDevDependencies).

My issue is thus resolved!

**Comment by julienrf** [comment]
Good to know that webpack css loaders can still be used with scalajs-bundler (that was unintended!).
