### ISSUE TITLE
`testHtmlFastOpt` and `testHtmlFullOpt` use incorrect file

### ISSUE THREAD

**Issue by dispalt** [scalacenter/scalajs-bundler#89]
The HTML that gets generated uses `[name]-test-[stage].js` vs `[name]-test-[stage]-bundle.js`.  It looks like it's looking at `fastOptJS in testHtmlFastOpt` for the file name. I made a quick fix in my own project, and would contribute it back but I don't really see where the bundle is named.  Obviously it's fairly hacky.

```scala
fastOptJS in testHtmlFastOpt in Test := {
      val f = (fastOptJS in testHtmlFastOpt in Test).value
      val fd = new File(f.data.getPath.stripSuffix(".js") + "-bundle.js")
      f.copy(fd)(f.metadata)
    }
```

**Comment by julienrf** [comment]
Thanks for reporting.
The bundle files are returned by the [`webpack` command](https://scalacenter.github.io/scalajs-bundler/api/latest/index.html#scalajsbundler.sbtplugin.ScalaJSBundlerPlugin$$autoImport$). I think the right implementation would be something like the following:

~~~ scala
fastOptJS in testHtmlFastOpt in Test := {
  (webpack in fastOptJS).value match {
    case Seq(bundle) => Attributed(bundle)((fastOptJS in testHtmlFastOpt).value.metadata)
    case _ => sys.error("testHtmlFastOpt task supports only exactly one bundle")
  }
}
~~~

What do you think?

**Comment by dispalt** [comment]
I like this much better, I haven't tested it though.  Shall I make the change on the website?

**Comment by julienrf** [comment]
What do you mean by “the website”?

**Comment by dispalt** [comment]
In the cookbooks sections.  Or, is this something that you fix in the plugin?

**Comment by julienrf** [comment]
That would be great if you could directly fix the plugin :)

You should add it to [this list](https://github.com/scalacenter/scalajs-bundler/blob/master/sbt-scalajs-bundler/src/main/scala/scalajsbundler/sbtplugin/ScalaJSBundlerPlugin.scala#L339) (and you should add a similar setting for `testHtmlFullOpt`, I think) and then add the following lines `> testHtmlFastOpt` and `> testHtmlFullOpt` at the end of [this file](https://github.com/scalacenter/scalajs-bundler/blob/master/sbt-scalajs-bundler/src/sbt-test/sbt-scalajs-bundler/static/test#L35).

**Comment by dispalt** [comment]
On it!

**Comment by raquo** [comment]
Is this related to https://github.com/scalacenter/scalajs-bundler/issues/89 or https://github.com/scalacenter/scalajs-bundler/issues/38 ? I'm getting "ReferenceError: exports is not defined" when trying to run tests with scala js bundler and jsdom... It seems that all three tickets refer to this issue?

**Comment by julienrf** [comment]
@raquo Are you using the `testHtmlFastOpt` task? Just running the tests with `test` should work if you added `requiresDOM in Test := true` to your build.

**Comment by raquo** [comment]
Thanks! I *think* I was using the `test` command with `jsDependencies += RuntimeDOM % Test` instead of the `requiresDOM` line you mentioned. Although I did try `testHtmlFastOpt` with the same result. Eventually I found this example https://github.com/scalacenter/scalajs-bundler/tree/master/sbt-scalajs-bundler/src/sbt-test/sbt-scalajs-bundler/static and now I'm using the config as you've suggested.

**Comment by raquo** [comment]
I'm now getting the same `exports is not defined` problem when trying to run tests with selenium using the `test` command. Is that this same bug manifesting, or does this look like an issue with `scalajs-env-selenium`? Or maybe I'm doing something wrong?

The relevant build.sbt part is:

    persistLauncher in Test := false
    
    requiresDOM in Test := true
    
    jsEnv in Test := new org.scalajs.jsenv.selenium.SeleniumJSEnv(org.scalajs.jsenv.selenium.Chrome())

PS sorry for hijacking this issue, it seems like it might be the same problem.

**Comment by julienrf** [comment]
It might be the same issue, indeed… This would require a bit of investigation.

**Comment by ramnivas** [comment]
I am also getting the same `exports is not defined` error with `jsEnv in Test := new org.scalajs.jsenv.selenium.SeleniumJSEnv(org.scalajs.jsenv.selenium.Chrome())`.

**Comment by atooni** [comment]
I am getting the same Problem in my project

**Comment by matthughes** [comment]
@raquo Hmm why would you have requiresDOM in Test if using Selenium as your JSEnv?  Doesn't the latter provide that inherently?   I thought the former's role was solely to download jsdom module.

**Comment by matthughes** [comment]
If you compare the loaders for the web app vs a test you see the following:

runner
```scala
var exports = window;
exports.require = window["ScalaJSBundlerLibrary"].require;
```

test
```scala
{
  var x0 = require("/project/target/scala-2.12/scalajs-bundler/test/project-test-fastopt.js");
  Object.keys(x0).forEach((function(x1) {
    return window[x1] = x0[x1]
  }))
}
```

Why do we define exports in the one but not the other?

**Comment by fkoehler** [comment]
I also run into this issue. I am unable to run any tests now. It is not related to Selenium. it looks like what @matthughes said that the test loader is not including i.e. the -bundle version?

**Comment by fkoehler** [comment]
In my very specific case I was able to fix the error by removing this line:

`jsEnv := new org.scalajs.jsenv.jsdomnodejs.JSDOMNodeJSEnv()`

Then a correct `codeWithJSDOMContext.js` was created in `scalajs-bundler-jsdom` and now the tests work.

**Comment by fbaierl** [comment]
Has there been any progress on this issue? Facing the same issue and `requireJsDomEnv in Test := true` does not seem to work.

**Comment by sjrd** [comment]
I believe this should be fixed when using Scala.js 1.x, with
```scala
requireJsDomEnv in Test := true
```
and with the task `testHtml` (which replaces `testHtmlFastOpt` and `testHtmlFullOpt` of Scala.js 0.6.x).

**Comment by fbaierl** [comment]
Alright thanks. I am still using Scala.js 0.6 so I guess I'll have to try to update. :)

**Comment by fbaierl** [comment]
Unfortunately we cannot update to Scala.js 1.0.1 yet since too many dependencies are still on 0.6. I'll need to look for a different solution. Thanks anyway @sjrd .
