### ISSUE TITLE
Don't ignore webpack errors

### ISSUE THREAD

**Issue by nigredo-tori** [scalacenter/scalajs-bundler#92]
At the moment any bunding errors are ignored by the webpack task.

Here's an [example project](https://github.com/nigredo-tori/various-examples/tree/master/scala/sbt-scalajs-bundler/webpack-bail). It contains an error (an unresolved module). But the `webpack` task succeeds!
```
$ sbt fastOptJS::webpack
<truncated>
[info] ERROR in ./js-resources-fastopt.js
[info] Module not found: Error: Cannot resolve module 'no-such-module' in /home/dmitry/work/various-examples/scala/sbt-scalajs-bundler/webpack-bail/target/scala-2.11/scalajs-bundler/main
[info]  @ ./js-resources-fastopt.js 1029:32-57
[success] Total time: 19 s, completed Jan 13, 2017 3:46:32 PM
```

The reason for this is a quirk of webpack itself: by default it always produces zero return code, even when errors are encountered. There are ways to change this behaviour, though: `--bail` command-line option and `bail` flag in configuration. I think scalajs-bundler should also expose this functionality, and/or fail on error by default.

Workaround: Setting `bail` config flag in a custom webpack config.

**Comment by julienrf** [comment]
Do you think this is fine if we *always* enable the `bail` option, without even providing a way to disable it? I see no reasons to not stop the build process in case of error during the bundling process.

**Comment by nigredo-tori** [comment]
My experience with both webpack and this project is superficial, so you might want to get a second opinion on this... As far as I can tell, the default behavior is mostly useful for live coding (webpack-dev-server). You have your own solution for this, which, as far as I can tell, doesn't rely on webpack, so I'd say there's not much to be gained by exposing this option just yet. I'd say it's better to use the `--bail` command-line option for the implementation, though - this should allow one to launch the live server in `target` without modifying the config.

**Comment by dispalt** [comment]
I think not bailing is a huge pain, so I am for the change!
