### ISSUE TITLE
Relax NPM dependency version conflict resolution

### ISSUE THREAD

**Issue by nigredo-tori** [scalacenter/scalajs-bundler#99]
Current implementation requires that for each NPM package all version descriptors match exactly (for example, `15.4.2` and `~15.4.2` don't match). So any such "conflict" must be resolved explicitly via `npmResolutions`. This is not a big problem at the moment, but is likely to become more of an issue as the number of libraries using the bundler grows.
There are two ways to deal with this I can think of:
1. Automatic resolution for such conflicts within the plugin itself. This would, however, require adding and maintaining conflict resolution code compatible with `package.json` specification.
2. A much simpler solution would be to delegate such resolution to `npm`/`yarn` themselves. `package.json` supports passing multiple version descriptors, which should be perfect for this purpose.

**Comment by julienrf** [comment]
> A much simpler solution would be to delegate such resolution to npm/yarn themselves.

That’s the best approach, in my opinion. I didn’t know we could pass multiple version descriptors in `package.json`, I just had a look at the spec and it seems we can indeed use `||` between version candidates, is this what you were thinking of?

**Comment by nigredo-tori** [comment]
@julienrf, `||` is disjunction. We need the opposite (conjunction), so that if any of the predicates don't match, the task fails. In `package.json` this just means adding the descriptors to space-separated list. E.g. `">=14.0.0 14.4.2 ^14.4.1"`.

**Comment by julienrf** [comment]
Oops, you’re right, disjunction is not what we want… Thank for your explanation.

**Comment by julienrf** [comment]
So, I think the way to go is to remove the `npmResolutions` key and to simply add all the versions of a same dependency in the `package.json` file, just as you explained.

**Comment by nigredo-tori** [comment]
In my opinion, `npmResolution` should stay. We still need an escape hatch to manually resolve a conflict. What if someone adds an overly specific descriptor for their package? I'd like to be able to override this.

**Comment by julienrf** [comment]
The current strategy is to use the `npmResolutions` only in the case where we have several versions of a same dependency. If we want to keep an escape hatch then the behavior should be the following when we have several versions of a same dependency: if there is an `npmResolution` for this dependency, use only this version, otherwise use all the versions (instead of failing, as we currently do). Does that sound good to you?

**Comment by nigredo-tori** [comment]
Yes, that's what I had in mind as well.
